DEFAULT_IGNORE_DIRS = {
    ".git",
    ".svn",
    ".hg",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
    "bower_components",
    ".venv",
    "venv",
    "env",
    ".env",
    ".tox",
    ".nox",
    "dist",
    "build",
    "_build",
    ".idea",
    ".vscode",
    ".vs",
    "target",
    "vendor",
    ".next",
    ".nuxt",
    "coverage",
    ".coverage",
    ".terraform",
    "egg-info",
}

DEFAULT_IGNORE_PATTERNS = [
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.so",
    "*.dylib",
    "*.dll",
    "*.o",
    "*.a",
    "*.exe",
    "*.bin",
    "*.class",
    "*.jar",
    "*.war",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "*.log",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.bmp",
    "*.ico",
    "*.svg",
    "*.webp",
    "*.mp3",
    "*.mp4",
    "*.avi",
    "*.mov",
    "*.wav",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.bz2",
    "*.xz",
    "*.rar",
    "*.7z",
    "*.pdf",
    "*.doc",
    "*.docx",
    "*.xls",
    "*.xlsx",
    "*.ppt",
    "*.pptx",
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.eot",
    "*.otf",
    "*.db",
    "*.sqlite",
    "*.sqlite3",
    ".DS_Store",
    "Thumbs.db",
    ".gitignore",
    ".gitattributes",
]

# Cache / output schema versions. Bumping a version invalidates the matching
# caches so an upgrade never silently reuses stale results.
RENDER_SCHEMA_VERSION = 2
LINT_CACHE_SCHEMA_VERSION = 2
ONEPDF_BLOCK_SCHEMA_VERSION = 2
SNAPSHOT_SCHEMA_VERSION = 1
